const img = (id, w = 800) =>
  `https://images.unsplash.com/${id}?auto=format&fit=crop&w=${w}&q=80`;

export const products = [
  // ── Electronics ──
  {
    id: "acoustic-over-ear-headphones",
    name: "Acoustic Over-Ear Headphones",
    category: "Electronics",
    categorySlug: "electronics",
    brand: "SoundMax",
    price: 299,
    rating: 4.7,
    reviews: 124,
    badge: "Best Seller",
    image: img("photo-1505740420928-5e560c06d30e"),
    description: "Immersive sound with deep bass and 40 hours of battery life.",
    features: ["40h battery life", "Active noise cancellation", "Bluetooth 5.3"],
    stock: 18,
  },
  {
    id: "nexar-pro-x-smartphone",
    name: "Nexar Pro X — 5G Flagship Smartphone",
    category: "Electronics",
    categorySlug: "electronics",
    brand: "Nexar",
    price: 849,
    oldPrice: 999,
    rating: 4.5,
    reviews: 128,
    badge: "Discount",
    image: img("photo-1511707171634-5f897ff02aa9"),
    description: "6.7-inch OLED display, aerospace-grade aluminum, pro-grade triple camera.",
    features: ['6.7" Super AMOLED (120Hz)', "50MP + 12MP + 8MP cameras", "IP68"],
    stock: 31,
  },
  {
    id: "techcorp-probook-x",
    name: "TechCorp ProBook X",
    category: "Electronics",
    categorySlug: "electronics",
    brand: "TechCorp",
    price: 1299,
    rating: 4.8,
    reviews: 120,
    badge: "Best Seller",
    image: img("photo-1496181133206-80ce9b88a853"),
    description: "Ultraportable productivity laptop with all-day battery.",
    features: ['14" 2.8K OLED', "32GB RAM", "1TB SSD", "18h battery"],
    stock: 9,
  },
  // ── Fashion ──
  {
    id: "heritage-leather-satchel",
    name: "Heritage Leather Satchel",
    category: "Fashion & Clothing",
    categorySlug: "fashion",
    brand: "Atlas",
    price: 215,
    rating: 4.9,
    reviews: 210,
    image: img("photo-1547949003-9792a18a2601"),
    description: "Full-grain leather, hand-stitched and built to last a lifetime.",
    features: ["Full-grain leather", "Hand-stitched", "Brass hardware"],
    stock: 4,
  },
  {
    id: "athletic-running-shoes",
    name: "AeroGlide Running Shoes",
    category: "Fashion & Clothing",
    categorySlug: "fashion",
    brand: "Stride",
    price: 120,
    oldPrice: 150,
    rating: 4.4,
    reviews: 210,
    badge: "Discount",
    image: img("photo-1542291026-7eec264c27ff"),
    description: "Lightweight, responsive running shoes for long-distance comfort.",
    features: ["Carbon plate", "Breathable mesh", "Energy-return foam"],
    stock: 55,
  },
  // ── Groceries ──
  {
    id: "ethiopian-yirgacheffe-coffee",
    name: "Ethiopian Yirgacheffe Coffee Beans",
    category: "Groceries",
    categorySlug: "groceries",
    brand: "Highland Roasters",
    price: 35,
    rating: 4.8,
    reviews: 312,
    badge: "Best Seller",
    image: img("photo-1559056199-641a0ac8b55e"),
    description: "Single-origin, washed-process beans with bright citrus and floral notes.",
    features: ["1kg bag", "Medium roast", "Single origin"],
    stock: 200,
  },
  {
    id: "organic-dates-premium",
    name: "Premium Medjool Dates (1kg)",
    category: "Groceries",
    categorySlug: "groceries",
    brand: "Desert Gold",
    price: 28,
    rating: 4.9,
    reviews: 445,
    badge: "Best Seller",
    image: img("photo-1558642452-9d2a7deb7f62"),
    description: "Plump, naturally sweet Medjool dates from Saudi Arabia.",
    features: ["1kg net", "No added sugar", "Rich in fibre"],
    stock: 150,
  },
  // ── Beauty ──
  {
    id: "african-black-soap",
    name: "Raw African Black Soap Bar",
    category: "Beauty Products",
    categorySlug: "beauty",
    brand: "Shea Heritage",
    price: 18,
    rating: 4.8,
    reviews: 562,
    badge: "Best Seller",
    image: img("photo-1556228720-195a672e8a03"),
    description: "Traditional Ghanaian black soap with shea butter and palm oil.",
    features: ["100% natural", "All skin types", "200g bar"],
    stock: 300,
  },
  {
    id: "shea-butter-moisturiser",
    name: "Whipped Shea Butter Moisturiser",
    category: "Beauty Products",
    categorySlug: "beauty",
    brand: "Shea Heritage",
    price: 29,
    rating: 4.9,
    reviews: 401,
    badge: "New",
    image: img("photo-1604654894610-df63bc536371"),
    description: "Ultra-rich whipped shea butter with baobab and marula oils.",
    features: ["Unrefined shea butter", "250ml jar", "No parabens"],
    stock: 85,
  },
  // ── Household ──
  {
    id: "artisanal-ceramic-vases-set",
    name: "Artisanal Ceramic Vases Set",
    category: "Household Items",
    categorySlug: "household",
    brand: "Heritage Crafts",
    price: 145,
    rating: 4.6,
    reviews: 89,
    image: img("photo-1578749556568-bc2c40e68b61"),
    description: "Handmade in Ethiopia, celebrating ancestral craftsmanship.",
    features: ["Set of 3", "Hand-thrown stoneware", "Food safe glaze"],
    stock: 7,
  },
  {
    id: "bamboo-kitchen-set",
    name: "Bamboo Kitchen Utensil Set",
    category: "Household Items",
    categorySlug: "household",
    brand: "EcoHome",
    price: 48,
    oldPrice: 65,
    rating: 4.7,
    reviews: 156,
    badge: "Discount",
    image: img("photo-1556909114-f6e7ad7d3136"),
    description: "Sustainably sourced bamboo kitchen set.",
    features: ["Set of 8 pieces", "Naturally antibacterial", "Heat resistant"],
    stock: 62,
  },
  // ── Accessories ──
  {
    id: "leather-minimalist-wallet",
    name: "Slim Leather Minimalist Wallet",
    category: "Accessories",
    categorySlug: "accessories",
    brand: "Atlas",
    price: 55,
    oldPrice: 75,
    rating: 4.7,
    reviews: 312,
    badge: "Discount",
    image: img("photo-1627123424574-724758594785"),
    description: "Slim bi-fold wallet in full-grain leather — 8 cards, RFID blocking.",
    features: ["Full-grain leather", "8 card slots", "RFID blocking"],
    stock: 95,
  },
  {
    id: "gold-statement-necklace",
    name: "Gold-Plated Statement Necklace",
    category: "Accessories",
    categorySlug: "accessories",
    brand: "Adorn",
    price: 72,
    rating: 4.8,
    reviews: 187,
    badge: "Best Seller",
    image: img("photo-1515562141207-7a88fb7ce338"),
    description: "18k gold-plated necklace inspired by ancient Nubian traditions.",
    features: ["18k gold plating", "Nickel-free", "Gift box included"],
    stock: 40,
  },
];

export function getProduct(id) {
  return products.find((p) => p.id === id);
}

export function byCategory(slug) {
  return products.filter((p) => p.categorySlug === slug);
}

export const categories = [
  {
    slug: "electronics",
    name: "Electronics",
    blurb: "Latest gadgets & tech essentials.",
    image: img("photo-1468495244123-6c6c332eeece"),
  },
  {
    slug: "fashion",
    name: "Fashion & Clothing",
    blurb: "Modern heritage style & apparel.",
    image: img("photo-1489987707025-afc232f7ea0f"),
  },
  {
    slug: "groceries",
    name: "Groceries",
    blurb: "Fresh regional produce, delivered.",
    image: img("photo-1542838132-92c53300491e"),
  },
  {
    slug: "beauty",
    name: "Beauty Products",
    blurb: "Premium skincare, naturally sourced.",
    image: img("photo-1596462502278-27bfdc403348"),
  },
  {
    slug: "household",
    name: "Household Items",
    blurb: "Crafted essentials for the home.",
    image: img("photo-1556909114-f6e7ad7d3136"),
  },
  {
    slug: "accessories",
    name: "Accessories",
    blurb: "Jewellery, bags, wallets & more.",
    image: img("photo-1515562141207-7a88fb7ce338"),
  },
];
